### Step 1) Register or create new user
POST https://microbloglite.herokuapp.com/api/users/
Content-Type: application/json

{
  "username": "jtranuserstuff",
  "fullName": "Jon Tran",
  "password": "notmypassword1"
}

### Step 2) Login
POST https://microbloglite.herokuapp.com/auth/login
Content-Type: application/json

{
  "username": "jtranuserstuff",
  "password": "notmypassword1"
}

### Step 3) GET Users
GET https://microbloglite.herokuapp.com/api/users/?limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp0cmFudXNlcnN0dWZmIiwiaWF0IjoxNjg3NTQ1MTI3LCJleHAiOjE2ODc2MzE1Mjd9.6iBwHMaaKDd-hqDnzNdoGdUkUo67tsqpdSXqonIg4-8

### Step 4) Add Post

### Step 5) GET Posts

### Step 6) DELETE Post