### Step 1) Register or create new user
POST https://microbloglite.herokuapp.com/api/users/
Content-Type: application/json

{
  "username": "jtranuserstuff",
  "fullName": "",
  "password": "notmypassword1"
}

### Step 2) Login
POST https://microbloglite.herokuapp.com/auth/login
Content-Type: application/json

{
  "username": "jtranuserstuff",
  "password": "notmypassword1"
}

### Step 3) GET Users
GET https://microbloglite.herokuapp.com/api/users/?limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp0cmFudXNlcnN0dWZmIiwiaWF0IjoxNjg3ODkyMDIzLCJleHAiOjE2ODc5Nzg0MjN9.bBK8nCb_Al0G_BbqnpKdotv_cZlScxx3tnYL5GS4PCU

### Step 4) Add Post
POST https://microbloglite.herokuapp.com/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp0cmFudXNlcnN0dWZmIiwiaWF0IjoxNjg3NTQ0NjMyLCJleHAiOjE2ODc2MzEwMzJ9.Coj0e5_Ryf2Kp1xIrpRVJctGMCGyBGyaBHbR6rFevYI

{
    "text": "Trying out life."
}

### Step 5) GET Posts
GET https://microbloglite.herokuapp.com/api/posts
Content-Type: application/json
Authorization: Bearer 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcnNoIiwiaWF0IjoxNjg3ODAzMTkzLCJleHAiOjE2ODc4ODk1OTN9.Y2uwK4-yre7PLlQ2BoevRtdi0aRMU-zF01QnXreodkw

### Step 6) DELETE Post
DELETE https://microbloglite.herokuapp.com/api/posts 
Content-Type: application/json
Authorization:  Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp0cmFudXNlcnN0dWZmIiwiaWF0IjoxNjg3NTQ0NjMyLCJleHAiOjE2ODc2MzEwMzJ9.Coj0e5_Ryf2Kp1xIrpRVJctGMCGyBGyaBHbR6rFevYI
